import NavBar from "@/components/global/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/global/Footer";
import Provider from "@/components/context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Provider>
          <NavBar />
          <main className="container mx-auto grow my-6">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
